sudo: required
services:
    - docker

before_install:
    - docker build -t dockerreactapp -f Dockerfile.dev .

script:
    - docker run -e CI=true dockerreactapp npm run test

deploy:
    provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: "ap-south-1"
    app: "docker-demo-app"
    env: "DockerDemoApp-env"
    bucket_name: "elasticbeanstalk-ap-south-1-813777477033"
    on:
        branch: master